version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        - DdEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./environment/backend.env
  
  db: 
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./environment/postgres.env

volumes:
  db-data: